### ISSUE TITLE
chapter 1 notebook - Cell 8

### ISSUE THREAD

**Issue by Esquire-gh** [TrainingByPackt/Data-Science-Projects-with-Python#2]
The comment above says "Has less than the number of rows..........". What has?

**Comment by klostest** [comment]
Hi Richard,
Regarding your first note, the data has been uploaded to github. Apologies,
it was not clear to me how the data should be provided.

For this comment, the jupyter notebook is not intended to be "stand-alone":
there is limited markdown and comments. Rather, it simply contains the code
which is explained in detail in the chapter. If this seems confusing, it
may be better to delete all the markdown cells from the notebooks.

Thanks, Steve

**Comment by Esquire-gh** [comment]
Sure. Thanks Steve. Then maybe you can make it in a way that someone can move between the chapter and the notebook easily. But it's okay for now. Thanks. Nice chapter by the way.

**Comment by klostest** [comment]
Thank you Richard. I realize that there isn't a correspondence between
section headings in the notebook versus the chapter, for Chapter 1, but
that I started doing this in Chapter 2. So I'll plan to revise the notebook
for Chapter 1 accordingly.
Best, Steve
